// ===== 背诵表数据（从维克多单词拆解手册提取） =====
const reciteData = [
    { name: 'a-', type: 'prefix', meaning: '不，无，在...', examples: ['ashamed', 'avoid', 'amazing', 'abroad', 'amusement'] },
    { name: 'ab-', type: 'prefix', meaning: '离开，偏离', examples: ['absent', 'ability'] },
    { name: 'ac-', type: 'prefix', meaning: '朝向（ad-同化）', examples: ['accept', 'accident'] },
    { name: 'ad-', type: 'prefix', meaning: '朝向，接近', examples: ['advice', 'additional', 'adventure', 'advertise', 'advantage'] },
    { name: 'af-', type: 'prefix', meaning: '朝向（ad-同化）', examples: ['afford', 'after', 'affect'] },
    { name: 'al-', type: 'prefix', meaning: '朝向（ad-同化）', examples: ['allow', 'alone', 'alarm', 'although'] },
    { name: 'an-', type: 'prefix', meaning: '不，无', examples: ['annoy', 'another'] },
    { name: 'ap-', type: 'prefix', meaning: '朝向（ad-同化）', examples: ['appear', 'appreciate', 'appearance'] },
    { name: 'apo-', type: 'prefix', meaning: '离开，远离', examples: ['apologize'] },
    { name: 'ar-', type: 'prefix', meaning: '朝向（ad-同化）', examples: ['arrange'] },
    { name: 'astro-', type: 'prefix', meaning: '星星，天体', examples: ['astronaut'] },
    { name: 'at-', type: 'prefix', meaning: '朝向（ad-同化）', examples: ['attractive', 'attention', 'attract', 'attitude'] },
    { name: 'be-', type: 'prefix', meaning: '使...，在...', examples: ['beyond', 'believe', 'belief', 'behave', 'belong'] },
    { name: 'bene-', type: 'prefix', meaning: '好，善', examples: ['benefit'] },
    { name: 'bio-', type: 'prefix', meaning: '生命，生物', examples: ['biology'] },
    { name: 'co-', type: 'prefix', meaning: '共同，一起', examples: ['cover', 'cooperate'] },
    { name: 'col-', type: 'prefix', meaning: '共同，一起（com-同化）', examples: ['college', 'collect'] },
    { name: 'com-', type: 'prefix', meaning: '共同，一起', examples: ['common', 'compete', 'communicate', 'competition', 'compare'] },
    { name: 'con-', type: 'prefix', meaning: '共同，一起（com-同化）', examples: ['conversation', 'continue', 'convenient', 'concentrate', 'contain'] },
    { name: 'contra-', type: 'prefix', meaning: '反对，相反', examples: ['control'] },
    { name: 'cor-', type: 'prefix', meaning: '共同，一起（com-同化）', examples: ['correct'] },
    { name: 'de-', type: 'prefix', meaning: '向下，去掉，相反', examples: ['decide', 'determined', 'design', 'describe', 'development'] },
    { name: 'di-', type: 'prefix', meaning: '二，双，分开', examples: ['direct', 'divide'] },
    { name: 'dif-', type: 'prefix', meaning: '分开，不（dis-变体）', examples: ['difference', 'difficult'] },
    { name: 'dis-', type: 'prefix', meaning: '不，消失，分开', examples: ['disappointed', 'disabled', 'disadvantage', 'display', 'discussion'] },
    { name: 'e-', type: 'prefix', meaning: '出，向外', examples: ['emotion', 'education', 'especially', 'equipment', 'event'] },
    { name: 'em-', type: 'prefix', meaning: '进入，使...（en-变体）', examples: ['embarrassed'] },
    { name: 'en-', type: 'prefix', meaning: '使...，进入', examples: ['endanger', 'energy', 'encourage'] },
    { name: 'enter-', type: 'prefix', meaning: '在...之间', examples: ['entertainment'] },
    { name: 'ex-', type: 'prefix', meaning: '出，向外，前任', examples: ['exchange', 'exist', 'exciting', 'excuse', 'explore'] },
    { name: 'for-', type: 'prefix', meaning: '离开，禁止', examples: ['forgive'] },
    { name: 'fore-', type: 'prefix', meaning: '在前，预先', examples: ['foreign'] },
    { name: 'ig-', type: 'prefix', meaning: '不（in-变体）', examples: ['ignore'] },
    { name: 'im-', type: 'prefix', meaning: '不，进入（in-变体）', examples: ['impress', 'impossible', 'importance', 'improve'] },
    { name: 'in-', type: 'prefix', meaning: '不，进入，在内', examples: ['influential', 'independence', 'invitation', 'involved', 'influence'] },
    { name: 'inter-', type: 'prefix', meaning: '在...之间', examples: ['international', 'interested', 'interrupt'] },
    { name: 'intro-', type: 'prefix', meaning: '向内，进入', examples: ['introduce'] },
    { name: 'kilo-', type: 'prefix', meaning: '千', examples: ['kilogramme'] },
    { name: 'mis-', type: 'prefix', meaning: '错误，坏', examples: ['mistake', 'mistaken'] },
    { name: 'ne-', type: 'prefix', meaning: '不，无', examples: ['necessary', 'neither', 'never'] },
    { name: 'neg-', type: 'prefix', meaning: '否定', examples: ['negative'] },
    { name: 'o-', type: 'prefix', meaning: '关于（ob-弱化）', examples: ['opinion'] },
    { name: 'ob-', type: 'prefix', meaning: '朝向，反对', examples: ['object'] },
    { name: 'of-', type: 'prefix', meaning: '朝向（ob-同化）', examples: ['official'] },
    { name: 'op-', type: 'prefix', meaning: '朝向，反对（ob-同化）', examples: ['opposite', 'opportunity'] },
    { name: 'over-', type: 'prefix', meaning: '过度，超过', examples: ['overnight', 'overcome'] },
    { name: 'abil', type: 'root', meaning: '能力', examples: ['ability'] },
    { name: 'abled', type: 'root', meaning: '能够', examples: ['disabled'] },
    { name: 'act', type: 'root', meaning: '做，行动', examples: ['exact', 'active', 'activity', 'actress'] },
    { name: 'advantage', type: 'root', meaning: '优势', examples: ['disadvantage'] },
    { name: 'air', type: 'root', meaning: '空气', examples: ['airport'] },
    { name: 'amin', type: 'root', meaning: '检查', examples: ['examine'] },
    { name: 'angr', type: 'root', meaning: '愤怒', examples: ['angry'] },
    { name: 'any', type: 'root', meaning: '任何', examples: ['anything', 'anyway'] },
    { name: 'appoint', type: 'root', meaning: '（待补充）', examples: ['disappointed'] },
    { name: 'argu', type: 'root', meaning: '争论', examples: ['argue'] },
    { name: 'arm', type: 'root', meaning: '武器，警报', examples: ['alarm'] },
    { name: 'art', type: 'root', meaning: '艺术', examples: ['artist', 'article'] },
    { name: 'athlet', type: 'root', meaning: '运动员', examples: ['athlete'] },
    { name: 'aver', type: 'root', meaning: '平均', examples: ['average'] },
    { name: 'awe', type: 'root', meaning: '（待补充）', examples: ['awful', 'awfully'] },
    { name: 'back', type: 'root', meaning: '后面', examples: ['background'] },
    { name: 'bal', type: 'root', meaning: '平衡', examples: ['balance'] },
    { name: 'barr', type: 'root', meaning: '阻碍', examples: ['embarrassed'] },
    { name: 'bas', type: 'root', meaning: '基础', examples: ['basic', 'basis'] },
    { name: 'beaut', type: 'root', meaning: '美', examples: ['beauty'] },
    { name: 'beauty', type: 'root', meaning: '美丽', examples: ['beautiful'] },
    { name: 'birth', type: 'root', meaning: '出生', examples: ['birthday'] },
    { name: 'black', type: 'root', meaning: '黑', examples: ['blackboard'] },
    { name: 'book', type: 'root', meaning: '（待补充）', examples: ['bookstore'] },
    { name: 'bor', type: 'root', meaning: '厌烦', examples: ['boring'] },
    { name: 'breath', type: 'root', meaning: '呼吸', examples: ['breathe'] },
    { name: 'brilli', type: 'root', meaning: '光辉', examples: ['brilliant'] },
    { name: 'broad', type: 'root', meaning: '宽广', examples: ['abroad'] },
    { name: 'build', type: 'root', meaning: '建造', examples: ['building'] },
    { name: 'busi', type: 'root', meaning: '忙碌，商业', examples: ['business'] },
    { name: 'calcul', type: 'root', meaning: '计算', examples: ['calculate'] },
    { name: 'care', type: 'root', meaning: '关心', examples: ['careless', 'caring', 'careful'] },
    { name: 'celebr', type: 'root', meaning: '庆祝', examples: ['celebrate'] },
    { name: 'cell', type: 'root', meaning: '细胞，优秀', examples: ['excellent'] },
    { name: 'centr', type: 'root', meaning: '中心', examples: ['central', 'concentrate'] },
    { name: 'centur', type: 'root', meaning: '百年', examples: ['century'] },
    { name: 'cept', type: 'root', meaning: '（待补充）', examples: ['accept'] },
    { name: 'cess', type: 'root', meaning: '走', examples: ['necessary'] },
    { name: 'change', type: 'root', meaning: '（待补充）', examples: ['exchange'] },
    { name: 'character', type: 'root', meaning: '性格', examples: ['characteristic'] },
    { name: 'chem', type: 'root', meaning: '化学', examples: ['chemistry'] },
    { name: 'chieve', type: 'root', meaning: '达到', examples: ['achieve'] },
    { name: 'cid', type: 'root', meaning: '（待补充）', examples: ['decide', 'accident'] },
    { name: 'circ', type: 'root', meaning: '圆', examples: ['circle'] },
    { name: 'cit', type: 'root', meaning: '市民，刺激', examples: ['exciting', 'excite', 'citizen'] },
    { name: 'class', type: 'root', meaning: '等级', examples: ['classic'] },
    { name: 'clean', type: 'root', meaning: '干净', examples: ['cleaner'] },
    { name: 'clear', type: 'root', meaning: '清楚', examples: ['clearly'] },
    { name: 'clim', type: 'root', meaning: '气候', examples: ['climate'] },
    { name: 'cloud', type: 'root', meaning: '云', examples: ['cloudy'] },
    { name: 'come', type: 'root', meaning: '来', examples: ['overcome'] },
    { name: 'corn', type: 'root', meaning: '角', examples: ['corner'] },
    { name: 'cour', type: 'root', meaning: '勇气', examples: ['courage', 'encourage'] },
    { name: 'cre', type: 'root', meaning: '创造', examples: ['creature'] },
    { name: 'crit', type: 'root', meaning: '批评', examples: ['criticize'] },
    { name: 'crowd', type: 'root', meaning: '人群', examples: ['crowded'] },
    { name: 'cur', type: 'root', meaning: '关心，治愈', examples: ['curious', 'cure'] },
    { name: 'cuse', type: 'root', meaning: '（待补充）', examples: ['excuse'] },
    { name: 'cuss', type: 'root', meaning: '（待补充）', examples: ['discussion'] },
    { name: 'dam', type: 'root', meaning: '损害', examples: ['damage'] },
    { name: 'danger', type: 'root', meaning: '危险', examples: ['endanger', 'dangerous'] },
    { name: 'deep', type: 'root', meaning: '深', examples: ['deeply'] },
    { name: 'dent', type: 'root', meaning: '牙齿', examples: ['dentist'] },
    { name: 'depend', type: 'root', meaning: '依赖', examples: ['independence'] },
    { name: 'digit', type: 'root', meaning: '数字', examples: ['digital'] },
    { name: 'dit', type: 'root', meaning: '（待补充）', examples: ['additional', 'editor'] },
    { name: 'docu', type: 'root', meaning: '文件', examples: ['documentary'] },
    { name: 'don', type: 'root', meaning: '给予', examples: ['donate'] },
    { name: 'down', type: 'root', meaning: '向下', examples: ['download'] },
    { name: 'duc', type: 'root', meaning: '引导', examples: ['educate', 'education', 'introduce'] },
    { name: 'dur', type: 'root', meaning: '持续', examples: ['during'] },
    { name: 'dustr', type: 'root', meaning: '（待补充）', examples: ['industry'] },
    { name: 'easy', type: 'root', meaning: '容易', examples: ['easy-going'] },
    { name: 'electr', type: 'root', meaning: '电', examples: ['electricity'] },
    { name: 'energ', type: 'root', meaning: '能量', examples: ['energetic'] },
    { name: 'engine', type: 'root', meaning: '引擎', examples: ['engineer'] },
    { name: 'erg', type: 'root', meaning: '工作，能量', examples: ['energy'] },
    { name: 'est', type: 'root', meaning: '存在', examples: ['interested'] },
    { name: 'extr', type: 'root', meaning: '极端', examples: ['extreme'] },
    { name: 'eye', type: 'root', meaning: '（待补充）', examples: ['eyesight'] },
    { name: 'fac', type: 'root', meaning: '脸，做', examples: ['facial'] },
    { name: 'fam', type: 'root', meaning: '名声', examples: ['famous'] },
    { name: 'famili', type: 'root', meaning: '熟悉', examples: ['familiar'] },
    { name: 'fantas', type: 'root', meaning: '幻想', examples: ['fantastic'] },
    { name: 'favour', type: 'root', meaning: '喜爱', examples: ['favourite'] },
    { name: 'fear', type: 'root', meaning: '害怕', examples: ['fearless'] },
    { name: 'fect', type: 'root', meaning: '（待补充）', examples: ['affect'] },
    { name: 'feel', type: 'root', meaning: '感觉', examples: ['feeling'] },
    { name: 'fem', type: 'root', meaning: '女性', examples: ['female'] },
    { name: 'fer', type: 'root', meaning: '携带', examples: ['difference'] },
    { name: 'fic', type: 'root', meaning: '做', examples: ['official', 'difficult'] },
    { name: 'fin', type: 'root', meaning: '结束，财务', examples: ['financial', 'finally'] },
    { name: 'fire', type: 'root', meaning: '（待补充）', examples: ['firework', 'fireman'] },
    { name: 'fit', type: 'root', meaning: '（待补充）', examples: ['benefit'] },
    { name: 'flu', type: 'root', meaning: '流动', examples: ['influential', 'influence'] },
    { name: 'fool', type: 'root', meaning: '愚蠢', examples: ['foolish'] },
    { name: 'ford', type: 'root', meaning: '（待补充）', examples: ['afford'] },
    { name: 'form', type: 'root', meaning: '形状', examples: ['formal'] },
    { name: 'fort', type: 'root', meaning: '力量', examples: ['comfortable'] },
    { name: 'fortun', type: 'root', meaning: '运气', examples: ['fortunate'] },
    { name: 'fraid', type: 'root', meaning: '（待补充）', examples: ['afraid'] },
    { name: 'friend', type: 'root', meaning: '朋友', examples: ['friendship'] },
    { name: 'fright', type: 'root', meaning: '惊吓', examples: ['frightened', 'frightening'] },
    { name: 'fun', type: 'root', meaning: '乐趣', examples: ['funny'] },
    { name: 'gener', type: 'root', meaning: '产生', examples: ['generation', 'generous'] },
    { name: 'give', type: 'root', meaning: '（待补充）', examples: ['forgive'] },
    { name: 'glob', type: 'root', meaning: '球', examples: ['global'] },
    { name: 'gold', type: 'root', meaning: '金', examples: ['golden'] },
    { name: 'govern', type: 'root', meaning: '统治', examples: ['government'] },
    { name: 'grace', type: 'root', meaning: '优雅', examples: ['graceful'] },
    { name: 'grad', type: 'root', meaning: '步，级', examples: ['gradual'] },
    { name: 'gramme', type: 'root', meaning: '克', examples: ['kilogramme'] },
    { name: 'gree', type: 'root', meaning: '同意', examples: ['agree'] },
    { name: 'green', type: 'root', meaning: '绿', examples: ['greenhouse'] },
    { name: 'grow', type: 'root', meaning: '生长', examples: ['grow-up'] },
    { name: 'hair', type: 'root', meaning: '头发', examples: ['haircut'] },
    { name: 'hand', type: 'root', meaning: '手', examples: ['handsome'] },
    { name: 'happy', type: 'root', meaning: '快乐', examples: ['happiness'] },
    { name: 'hard', type: 'root', meaning: '硬', examples: ['hard-working', 'hardly'] },
    { name: 'hav', type: 'root', meaning: '有', examples: ['behaviour'] },
    { name: 'have', type: 'root', meaning: '有', examples: ['behave'] },
    { name: 'heal', type: 'root', meaning: '健康', examples: ['health'] },
    { name: 'heart', type: 'root', meaning: '心', examples: ['heartbroken'] },
    { name: 'heavy', type: 'root', meaning: '重', examples: ['heavily'] },
    { name: 'her', type: 'root', meaning: '她的', examples: ['herself', 'hers'] },
    { name: 'histor', type: 'root', meaning: '历史', examples: ['history', 'historical'] },
    { name: 'holi', type: 'root', meaning: '神圣', examples: ['holiday'] },
    { name: 'hospit', type: 'root', meaning: '客人', examples: ['hospital'] },
    { name: 'hunt', type: 'root', meaning: '打猎', examples: ['hunter'] },
    { name: 'ign', type: 'root', meaning: '不知道', examples: ['foreign'] },
    { name: 'ill', type: 'root', meaning: '病', examples: ['illness'] },
    { name: 'imag', type: 'root', meaning: '想象', examples: ['imagination'] },
    { name: 'influenza', type: 'root', meaning: '流感', examples: ['flu'] },
    { name: 'ist', type: 'root', meaning: '站立', examples: ['exist'] },
    { name: 'ither', type: 'root', meaning: '（待补充）', examples: ['neither'] },
    { name: 'ject', type: 'root', meaning: '投掷', examples: ['object'] },
    { name: 'jog', type: 'root', meaning: '（待补充）', examples: ['jogging'] },
    { name: 'kind', type: 'root', meaning: '善良', examples: ['kindness'] },
    { name: 'know', type: 'root', meaning: '知道', examples: ['knowledge'] },
    { name: 'laboratory', type: 'root', meaning: '实验室', examples: ['lab'] },
    { name: 'land', type: 'root', meaning: '土地', examples: ['landscape'] },
    { name: 'lap', type: 'root', meaning: '膝盖', examples: ['laptop'] },
    { name: 'large', type: 'root', meaning: '大', examples: ['largely'] },
    { name: 'late', type: 'root', meaning: '晚', examples: ['lately', 'latest'] },
    { name: 'law', type: 'root', meaning: '法律', examples: ['lawyer'] },
    { name: 'learn', type: 'root', meaning: '学习', examples: ['learner', 'learned'] },
    { name: 'lect', type: 'root', meaning: '收集，讲', examples: ['lecture', 'collect'] },
    { name: 'leg', type: 'root', meaning: '法律', examples: ['college'] },
    { name: 'lief', type: 'root', meaning: '相信', examples: ['belief'] },
    { name: 'lieve', type: 'root', meaning: '相信', examples: ['believe'] },
    { name: 'lightn', type: 'root', meaning: '光', examples: ['lightning'] },
    { name: 'like', type: 'root', meaning: '喜欢', examples: ['dislike', 'likely'] },
    { name: 'limit', type: 'root', meaning: '限制', examples: ['limited'] },
    { name: 'line', type: 'root', meaning: '线', examples: ['online'] },
    { name: 'liter', type: 'root', meaning: '文字', examples: ['literature'] },
    { name: 'live', type: 'root', meaning: '活', examples: ['alive', 'lively', 'living'] },
    { name: 'loc', type: 'root', meaning: '地方', examples: ['local'] },
    { name: 'log', type: 'root', meaning: '说', examples: ['apologize'] },
    { name: 'logy', type: 'root', meaning: '学科', examples: ['biology'] },
    { name: 'lone', type: 'root', meaning: '孤独', examples: ['lonely'] },
    { name: 'long', type: 'root', meaning: '长', examples: ['along', 'belong'] },
    { name: 'lose', type: 'root', meaning: '失去', examples: ['lost'] },
    { name: 'loud', type: 'root', meaning: '（待补充）', examples: ['aloud'] },
    { name: 'low', type: 'root', meaning: '低', examples: ['allow'] },
    { name: 'luck', type: 'root', meaning: '运气', examples: ['luckily'] },
    { name: 'man', type: 'root', meaning: '人', examples: ['man-made'] },
    { name: 'mathematics', type: 'root', meaning: '数学', examples: ['maths'] },
    { name: 'maze', type: 'root', meaning: '（待补充）', examples: ['amazing', 'amazed'] },
    { name: 'mean', type: 'root', meaning: '意思', examples: ['meaning', 'meanwhile'] },
    { name: 'medic', type: 'root', meaning: '医药', examples: ['medical'] },
    { name: 'ment', type: 'root', meaning: '心，想', examples: ['mention'] },
    { name: 'merg', type: 'root', meaning: '沉浸', examples: ['emergency'] },
    { name: 'mob', type: 'root', meaning: '移动', examples: ['mobile'] },
    { name: 'mod', type: 'root', meaning: '方式', examples: ['model', 'modern'] },
    { name: 'mon', type: 'root', meaning: '公共', examples: ['common'] },
    { name: 'mot', type: 'root', meaning: '动', examples: ['emotion'] },
    { name: 'mount', type: 'root', meaning: '山', examples: ['mountain'] },
    { name: 'move', type: 'root', meaning: '移动', examples: ['movement'] },
    { name: 'mun', type: 'root', meaning: '（待补充）', examples: ['communicate'] },
    { name: 'muse', type: 'root', meaning: '沉思', examples: ['museum', 'amusement'] },
    { name: 'music', type: 'root', meaning: '音乐', examples: ['musician'] },
    { name: 'my', type: 'root', meaning: '我的', examples: ['myself'] },
    { name: 'nat', type: 'root', meaning: '出生，自然', examples: ['nature', 'nation', 'native'] },
    { name: 'nation', type: 'root', meaning: '国家', examples: ['international', 'national'] },
    { name: 'naught', type: 'root', meaning: '（待补充）', examples: ['naughty'] },
    { name: 'naut', type: 'root', meaning: '航行', examples: ['astronaut'] },
    { name: 'near', type: 'root', meaning: '近', examples: ['nearly'] },
    { name: 'neck', type: 'root', meaning: '脖子', examples: ['necklace'] },
    { name: 'neg', type: 'root', meaning: '否定', examples: ['negative'] },
    { name: 'nerv', type: 'root', meaning: '神经', examples: ['nervous'] },
    { name: 'net', type: 'root', meaning: '网', examples: ['network'] },
    { name: 'news', type: 'root', meaning: '新闻', examples: ['newspaper'] },
    { name: 'night', type: 'root', meaning: '夜', examples: ['overnight'] },
    { name: 'no', type: 'root', meaning: '不', examples: ['nothing'] },
    { name: 'nore', type: 'root', meaning: '（待补充）', examples: ['ignore'] },
    { name: 'norm', type: 'root', meaning: '标准', examples: ['normal'] },
    { name: 'north', type: 'root', meaning: '北', examples: ['northern'] },
    { name: 'not', type: 'root', meaning: '注意', examples: ['notice'] },
    { name: 'note', type: 'root', meaning: '（待补充）', examples: ['notebook'] },
    { name: 'nov', type: 'root', meaning: '新', examples: ['novel'] },
    { name: 'now', type: 'root', meaning: '现在', examples: ['nowadays'] },
    { name: 'noy', type: 'root', meaning: '烦恼', examples: ['annoy'] },
    { name: 'one', type: 'root', meaning: '一', examples: ['alone'] },
    { name: 'open', type: 'root', meaning: '开', examples: ['opening'] },
    { name: 'oper', type: 'root', meaning: '工作', examples: ['cooperate', 'opera', 'operate'] },
    { name: 'ord', type: 'root', meaning: '（待补充）', examples: ['order'] },
    { name: 'ordin', type: 'root', meaning: '顺序', examples: ['ordinary'] },
    { name: 'organ', type: 'root', meaning: '器官', examples: ['organization'] },
    { name: 'other', type: 'root', meaning: '其他', examples: ['otherwise', 'another'] },
    { name: 'out', type: 'root', meaning: '出', examples: ['outgoing'] },
    { name: 'own', type: 'root', meaning: '自己的', examples: ['owner'] },
    { name: 'pain', type: 'root', meaning: '痛', examples: ['painless'] },
    { name: 'paint', type: 'root', meaning: '画', examples: ['painting'] },
    { name: 'paper', type: 'root', meaning: '纸', examples: ['paper-cut'] },
    { name: 'par', type: 'root', meaning: '（待补充）', examples: ['compare'] },
    { name: 'park', type: 'root', meaning: '公园', examples: ['parking'] },
    { name: 'partic', type: 'root', meaning: '部分', examples: ['particular'] },
    { name: 'pear', type: 'root', meaning: '出现', examples: ['appear', 'appearance'] },
    { name: 'per', type: 'root', meaning: '尝试', examples: ['experiment'] },
    { name: 'peri', type: 'root', meaning: '尝试', examples: ['experience'] },
    { name: 'pet', type: 'root', meaning: '追求', examples: ['compete', 'competition'] },
    { name: 'pin', type: 'root', meaning: '针', examples: ['opinion'] },
    { name: 'plain', type: 'root', meaning: '平', examples: ['explain'] },
    { name: 'play', type: 'root', meaning: '（待补充）', examples: ['display'] },
    { name: 'ple', type: 'root', meaning: '满', examples: ['complete'] },
    { name: 'plor', type: 'root', meaning: '探索', examples: ['explore'] },
    { name: 'port', type: 'root', meaning: '携带', examples: ['importance'] },
    { name: 'portun', type: 'root', meaning: '机会', examples: ['opportunity'] },
    { name: 'posit', type: 'root', meaning: '放置', examples: ['opposite'] },
    { name: 'possible', type: 'root', meaning: '可能', examples: ['impossible'] },
    { name: 'preci', type: 'root', meaning: '价格', examples: ['appreciate'] },
    { name: 'press', type: 'root', meaning: '压', examples: ['impress', 'express'] },
    { name: 'prove', type: 'root', meaning: '证明', examples: ['improve'] },
    { name: 'quip', type: 'root', meaning: '（待补充）', examples: ['equipment'] },
    { name: 'range', type: 'root', meaning: '排列', examples: ['arrange'] },
    { name: 'rect', type: 'root', meaning: '直', examples: ['correct', 'direct'] },
    { name: 'rol', type: 'root', meaning: '控制', examples: ['control'] },
    { name: 'rupt', type: 'root', meaning: '破裂', examples: ['interrupt'] },
    { name: 'scrib', type: 'root', meaning: '写', examples: ['describe'] },
    { name: 'sent', type: 'root', meaning: '感觉', examples: ['absent'] },
    { name: 'sham', type: 'root', meaning: '羞愧', examples: ['ashamed'] },
    { name: 'sign', type: 'root', meaning: '标记', examples: ['design'] },
    { name: 'sleep', type: 'root', meaning: '睡', examples: ['asleep'] },
    { name: 'special', type: 'root', meaning: '特别', examples: ['especially'] },
    { name: 'tain', type: 'root', meaning: '拿住', examples: ['entertainment', 'contain'] },
    { name: 'take', type: 'root', meaning: '拿', examples: ['mistake'] },
    { name: 'taken', type: 'root', meaning: '拿', examples: ['mistaken'] },
    { name: 'tent', type: 'root', meaning: '伸', examples: ['attention'] },
    { name: 'ter', type: 'root', meaning: '（待补充）', examples: ['after'] },
    { name: 'termin', type: 'root', meaning: '界限', examples: ['determined'] },
    { name: 'though', type: 'root', meaning: '虽然', examples: ['although'] },
    { name: 'tin', type: 'root', meaning: '保持', examples: ['continue'] },
    { name: 'tit', type: 'root', meaning: '态度', examples: ['attitude'] },
    { name: 'tract', type: 'root', meaning: '拉', examples: ['attractive', 'attract'] },
    { name: 'vail', type: 'root', meaning: '价值', examples: ['available'] },
    { name: 'vant', type: 'root', meaning: '来', examples: ['advantage'] },
    { name: 'velop', type: 'root', meaning: '（待补充）', examples: ['development'] },
    { name: 'ven', type: 'root', meaning: '（待补充）', examples: ['convenient'] },
    { name: 'vent', type: 'root', meaning: '（待补充）', examples: ['adventure', 'invent', 'event'] },
    { name: 'ver', type: 'root', meaning: '真实', examples: ['cover', 'never'] },
    { name: 'vers', type: 'root', meaning: '转', examples: ['conversation'] },
    { name: 'vert', type: 'root', meaning: '转', examples: ['advertise'] },
    { name: 'vice', type: 'root', meaning: '看', examples: ['advice'] },
    { name: 'vid', type: 'root', meaning: '看', examples: ['divide'] },
    { name: 'vis', type: 'root', meaning: '（待补充）', examples: ['advise'] },
    { name: 'vit', type: 'root', meaning: '生命', examples: ['invitation'] },
    { name: 'void', type: 'root', meaning: '空', examples: ['avoid'] },
    { name: 'volv', type: 'root', meaning: '滚动', examples: ['involved'] },
    { name: 'wake', type: 'root', meaning: '醒', examples: ['awake'] },
    { name: 'weblog', type: 'root', meaning: '网络日志', examples: ['blog'] },
    { name: 'yond', type: 'root', meaning: '那边', examples: ['beyond'] },
    { name: '-able', type: 'suffix', meaning: '能...的', examples: ['comfortable', 'available'] },
    { name: '-age', type: 'suffix', meaning: '状态，集合', examples: ['courage', 'message', 'average', 'manage', 'damage'] },
    { name: '-al', type: 'suffix', meaning: '...的（形容词）', examples: ['financial', 'global', 'facial', 'historical', 'hospital'] },
    { name: '-alis', type: 'suffix', meaning: '...的（形容词，拉丁语源）', examples: ['financial', 'global', 'facial', 'historical', 'hospital'] },
    { name: '-ance', type: 'suffix', meaning: '状态，性质（名词）', examples: ['importance', 'difference', 'influence', 'balance', 'licence'] },
    { name: '-ant', type: 'suffix', meaning: '...的 / ...者', examples: ['brilliant'] },
    { name: '-ary', type: 'suffix', meaning: '...的 / 场所', examples: ['ordinary', 'necessary', 'documentary'] },
    { name: '-ate', type: 'suffix', meaning: '使... / 做...', examples: ['appreciate', 'conversation', 'calculate', 'fascinate', 'invitation'] },
    { name: '-ation', type: 'suffix', meaning: '动作，状态（名词）', examples: ['organization'] },
    { name: '-ative', type: 'suffix', meaning: '有...倾向的', examples: ['negative'] },
    { name: '-ed', type: 'suffix', meaning: '...的（过去分词）', examples: ['disappointed', 'limited', 'involved', 'determined', 'interested'] },
    { name: '-ence', type: 'suffix', meaning: '状态，性质（名词）', examples: ['independence', 'difference', 'influence', 'licence', 'experience'] },
    { name: '-ent', type: 'suffix', meaning: '...的 / ...者', examples: ['judgement', 'moment', 'movement', 'amusement', 'government'] },
    { name: '-er', type: 'suffix', meaning: '...的人 / 比较级', examples: ['learner', 'elder', 'member', 'order', 'junior'] },
    { name: '-ess', type: 'suffix', meaning: '阴性 / 状态', examples: ['fearless', 'happiness', 'kindness', 'business', 'illness'] },
    { name: '-ful', type: 'suffix', meaning: '充满...的', examples: ['grateful', 'graceful', 'awful', 'beautiful', 'careful'] },
    { name: '-ial', type: 'suffix', meaning: '...的（形容词）', examples: ['official'] },
    { name: '-ian', type: 'suffix', meaning: '...的人 / ...的', examples: ['musician'] },
    { name: '-ic', type: 'suffix', meaning: '...的（形容词）', examples: ['magic', 'classic', 'fantastic', 'energetic', 'basic'] },
    { name: '-ikos', type: 'suffix', meaning: '...的（希腊语源）', examples: ['magic', 'classic', 'fantastic', 'energetic', 'basic'] },
    { name: '-ing', type: 'suffix', meaning: '正在...的 / 动名词', examples: ['amazing', 'exciting', 'painting', 'meaning', 'jogging'] },
    { name: '-io', type: 'suffix', meaning: '动作，状态（名词变体）', examples: ['emotion', 'attention', 'million', 'competition', 'nation'] },
    { name: '-ion', type: 'suffix', meaning: '动作，状态（名词）', examples: ['conversation', 'emotion', 'invitation', 'attention', 'million'] },
    { name: '-ish', type: 'suffix', meaning: '有点...的', examples: ['foolish'] },
    { name: '-ist', type: 'suffix', meaning: '...的人 / 主义者', examples: ['dentist', 'artist'] },
    { name: '-ity', type: 'suffix', meaning: '性质，状态（名词）', examples: ['electricity', 'opportunity', 'ability', 'activity'] },
    { name: '-ive', type: 'suffix', meaning: '有...倾向的', examples: ['active', 'native', 'attractive'] },
    { name: '-ize', type: 'suffix', meaning: '使...化', examples: ['apologize', 'organization', 'criticize'] },
    { name: '-less', type: 'suffix', meaning: '没有...的', examples: ['painless'] },
    { name: '-ly', type: 'suffix', meaning: '...地（副词）', examples: ['nearly', 'hardly', 'heavily', 'finally', 'lively'] },
    { name: '-or', type: 'suffix', meaning: '...的人', examples: ['emperor', 'junior', 'editor'] },
    { name: '-osus', type: 'suffix', meaning: '充满...的（拉丁语源）', examples: ['curious', 'nervous', 'dangerous', 'generous', 'famous'] },
    { name: '-ous', type: 'suffix', meaning: '充满...的', examples: ['curious', 'nervous', 'dangerous', 'generous', 'famous'] },
    { name: '-ship', type: 'suffix', meaning: '身份，关系', examples: ['friendship'] },
    { name: '-some', type: 'suffix', meaning: '引起...的', examples: ['handsome'] },
    { name: '-ture', type: 'suffix', meaning: '动作，结果（名词）', examples: ['literature', 'creature'] },
    { name: '-ty', type: 'suffix', meaning: '性质，状态（名词）', examples: ['duty'] },
    { name: '-ure', type: 'suffix', meaning: '动作，结果（名词）', examples: ['adventure', 'nature', 'lecture'] },
    { name: '-wise', type: 'suffix', meaning: '方式，方向', examples: ['otherwise'] },
    { name: '-y', type: 'suffix', meaning: '...的 / 状态', examples: ['chemistry', 'history', 'crazy', 'empty', 'beauty'] },
];